spring.application.name=AirbnbBackend


#server.servlet.context-path=/api/v1
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

frontend.url=http://localhost:8080

# Default profile
spring.profiles.active=${SPRING_PROFILES_ACTIVE}

stripe.secret.key=${STRIPE_SECRET}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
jwt.secretKey=${JWT_SECRET}

spring.flyway.enabled=true